export const SubTypes = {
    SET_CHECKOUT_SUB: 'SET_CHECKOUT_SUB',
    SET_GYM_NAME: 'SET_GYM_NAME',
    SET_PACKAGE_TYPE: 'SET_PACKAGE_TYPE',
    SET_SELECTED_PACKAGE: 'SET_SELECTED_PACKAGE',
    TOGGLE_CALENDAR_HIDDEN: 'TOGGLE_CALENDAR_HIDDEN',
    SET_SELECTED_DATE: 'SET_SELECTED_DATE',
    CLEAR_SUB: 'CLEAR_SUB'
}